import React, { ReactNode } from "react";
import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "../../components/ui/theme-provider";
import { SpeedInsights} from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";

const inter = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Navarrete Science",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: { apple: '/icon-192x192.png' },
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <ThemeProvider attribute="class" enableSystem defaultTheme="system" disableTransitionOnChange>
        <body className={`${inter.className} h-dvh bg-neutral-900`}>
          {children}
          <Analytics />
          </body>
      </ThemeProvider>
      <SpeedInsights />
    </html>
  );
}
